import React, { FC } from 'react';
import { IconBaseProps } from 'react-icons';
import {
  FiShoppingBag,
  FiArrowRight,
  FiTrash2,
  FiMinus,
  FiPlus,
  FiX,
  FiClock,
  FiPackage,
  FiTruck,
  FiCheckCircle,
  FiXCircle,
  FiArrowLeft,
  FiMapPin as FiMapPinIcon,
  FiPhone as FiPhoneIcon,
  FiMail as FiMailIcon,
  FiFilter,
  FiChevronUp,
  FiChevronDown,
  FiSearch,
  FiChevronLeft,
  FiChevronRight,
  FiShoppingCart,
  FiHeart,
  FiShare2,
  FiUser,
  FiMenu,
  FiCreditCard,
  FiRefreshCcw,
  FiHeadphones,
  FiGift,
  FiStar,
  FiLock,
  FiLoader,
  FiBarChart,
  FiFolder,
  FiMessageSquare,
  FiLogOut,
  FiSettings,
  FiTrendingUp,
  FiTrendingDown,
  FiDollarSign,
  FiUsers,
  FiEye,
  FiAlertCircle
} from 'react-icons/fi';
import { FaMapPin, FaPhone, FaEnvelope, FaFacebookF, FaTwitter, FaInstagram, FaLinkedinIn, FaGoogle } from 'react-icons/fa';

export const Icons = {
  ShoppingBag: FiShoppingBag as FC<IconBaseProps>,
  ArrowRight: FiArrowRight as FC<IconBaseProps>,
  Trash2: FiTrash2 as FC<IconBaseProps>,
  Minus: FiMinus as FC<IconBaseProps>,
  Plus: FiPlus as FC<IconBaseProps>,
  X: FiX as FC<IconBaseProps>,
  Clock: FiClock as FC<IconBaseProps>,
  Package: FiPackage as FC<IconBaseProps>,
  Truck: FiTruck as FC<IconBaseProps>,
  CheckCircle: FiCheckCircle as FC<IconBaseProps>,
  XCircle: FiXCircle as FC<IconBaseProps>,
  ArrowLeft: FiArrowLeft as FC<IconBaseProps>,
  MapPin: FaMapPin as FC<IconBaseProps>,
  Phone: FaPhone as FC<IconBaseProps>,
  Mail: FaEnvelope as FC<IconBaseProps>,
  Filter: FiFilter as FC<IconBaseProps>,
  ChevronUp: FiChevronUp as FC<IconBaseProps>,
  ChevronDown: FiChevronDown as FC<IconBaseProps>,
  Search: FiSearch as FC<IconBaseProps>,
  ChevronLeft: FiChevronLeft as FC<IconBaseProps>,
  ChevronRight: FiChevronRight as FC<IconBaseProps>,
  ShoppingCart: FiShoppingCart as FC<IconBaseProps>,
  Heart: FiHeart as FC<IconBaseProps>,
  Share2: FiShare2 as FC<IconBaseProps>,
  User: FiUser as FC<IconBaseProps>,
  Menu: FiMenu as FC<IconBaseProps>,
  CreditCard: FiCreditCard as FC<IconBaseProps>,
  RefreshCcw: FiRefreshCcw as FC<IconBaseProps>,
  Headphones: FiHeadphones as FC<IconBaseProps>,
  Gift: FiGift as FC<IconBaseProps>,
  Star: FiStar as FC<IconBaseProps>,
  FacebookF: FaFacebookF as FC<IconBaseProps>,
  Twitter: FaTwitter as FC<IconBaseProps>,
  Instagram: FaInstagram as FC<IconBaseProps>,
  LinkedinIn: FaLinkedinIn as FC<IconBaseProps>,
  Lock: FiLock as FC<IconBaseProps>,
  Loader: FiLoader as FC<IconBaseProps>,
  Google: FaGoogle as FC<IconBaseProps>,
  // Admin icons
  BarChart3: FiBarChart as FC<IconBaseProps>,
  FolderOpen: FiFolder as FC<IconBaseProps>,
  MessageSquare: FiMessageSquare as FC<IconBaseProps>,
  LogOut: FiLogOut as FC<IconBaseProps>,
  Settings: FiSettings as FC<IconBaseProps>,
  TrendingUp: FiTrendingUp as FC<IconBaseProps>,
  TrendingDown: FiTrendingDown as FC<IconBaseProps>,
  DollarSign: FiDollarSign as FC<IconBaseProps>,
  Users: FiUsers as FC<IconBaseProps>,
  Eye: FiEye as FC<IconBaseProps>,
  AlertCircle: FiAlertCircle as FC<IconBaseProps>,
};